// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queries} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function GetAccounts():Promise<Array<queries.Account>>;

export function Greet(arg1:string):Promise<string>;

export function ShowDialog():Promise<void>;
