// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function GetAccounts():Promise<Array<database.Account>>;

export function Greet(arg1:string):Promise<string>;

export function ShowDialog():Promise<void>;
