// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
