// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queries} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function CreateReceipt(arg1:number,arg2:string,arg3:string):Promise<queries.Receipt>;

export function DeleteReceipt(arg1:number):Promise<void>;

export function GetAllAccounts():Promise<Array<queries.Account>>;

export function GetAllReceipts():Promise<Array<queries.Receipt>>;

export function GetReceiptById(arg1:number):Promise<queries.Receipt>;

export function GetTotalBalance():Promise<number>;

export function GetTotalSpent():Promise<number>;

export function GetTotalSpentByDateRange(arg1:string,arg2:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function ShowDialog():Promise<void>;
