// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProfile(arg1) {
  return window['go']['main']['App']['ActivateProfile'](arg1);
}

export function CreateReceipt(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateReceipt'](arg1, arg2, arg3);
}

export function DeleteReceipt(arg1) {
  return window['go']['main']['App']['DeleteReceipt'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAllReceipts() {
  return window['go']['main']['App']['GetAllReceipts']();
}

export function GetReceiptById(arg1) {
  return window['go']['main']['App']['GetReceiptById'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ShowDialog() {
  return window['go']['main']['App']['ShowDialog']();
}
