// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
)

type Account struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Type         string `json:"type"`
	Bank         string `json:"bank"`
	BalanceCents int64  `json:"balance_cents"`
}

type AppSetting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Client struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Phone              sql.NullString `json:"phone"`
	CreditBalanceCents sql.NullInt64  `json:"credit_balance_cents"`
}

type Product struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	PriceCents int64          `json:"price_cents"`
	Stock      sql.NullInt64  `json:"stock"`
	Category   sql.NullString `json:"category"`
	ImagePath  sql.NullString `json:"image_path"`
}

type Receipt struct {
	ID          int64          `json:"id"`
	AccountID   int64          `json:"account_id"`
	AmountCents int64          `json:"amount_cents"`
	Date        string         `json:"date"`
	Description sql.NullString `json:"description"`
	Type        string         `json:"type"`
}

type StoreSale struct {
	ID         int64         `json:"id"`
	Date       sql.NullTime  `json:"date"`
	ClientID   sql.NullInt64 `json:"client_id"`
	TotalCents int64         `json:"total_cents"`
	IsCredit   sql.NullBool  `json:"is_credit"`
}

type Transaction struct {
	ID          int64          `json:"id"`
	Date        sql.NullTime   `json:"date"`
	AmountCents int64          `json:"amount_cents"`
	AccountID   sql.NullInt64  `json:"account_id"`
	Category    sql.NullString `json:"category"`
	Note        sql.NullString `json:"note"`
	ReceiptPath sql.NullString `json:"receipt_path"`
}
