// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (amount, date, description)
VALUES(?, ?, ?)
RETURNING id, amount, date, description
`

type CreateReceiptParams struct {
	Amount      float64        `json:"amount"`
	Date        string         `json:"date"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt, arg.Amount, arg.Date, arg.Description)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const deleteReceiptById = `-- name: DeleteReceiptById :exec
DELETE FROM receipts WHERE id = ?
`

func (q *Queries) DeleteReceiptById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceiptById, id)
	return err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, name, type, balance_cents FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReceipts = `-- name: GetAllReceipts :many
SELECT id, amount, date, description FROM receipts ORDER BY id DESC
`

func (q *Queries) GetAllReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, getAllReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Date,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT value FROM app_settings
WHERE key = ? LIMIT 1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getReceiptById = `-- name: GetReceiptById :one
SELECT id, amount, date, description FROM receipts WHERE id = ?
`

func (q *Queries) GetReceiptById(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptById, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const setAppSetting = `-- name: SetAppSetting :exec

INSERT OR REPLACE INTO app_settings (key, value)
VALUES (?, ?)
`

type SetAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// iceberg/database/query.sql
func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, setAppSetting, arg.Key, arg.Value)
	return err
}
