// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package queries

import (
	"context"
	"database/sql"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type, bank, balance_cents)
VALUES (?, ?, ?, ?)
RETURNING id, name, type, bank, balance_cents
`

type CreateAccountParams struct {
	Name         string `json:"name"`
	Type         string `json:"type"`
	Bank         string `json:"bank"`
	BalanceCents int64  `json:"balance_cents"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Type,
		arg.Bank,
		arg.BalanceCents,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Bank,
		&i.BalanceCents,
	)
	return i, err
}

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (amount_cents, date, description)
VALUES (?, ?, ?)
RETURNING id, amount_cents, date, description
`

type CreateReceiptParams struct {
	AmountCents int64          `json:"amount_cents"`
	Date        string         `json:"date"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt, arg.AmountCents, arg.Date, arg.Description)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.AmountCents,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE
FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteReceiptById = `-- name: DeleteReceiptById :exec
DELETE
FROM receipts
WHERE id = ?
`

func (q *Queries) DeleteReceiptById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteReceiptById, id)
	return err
}

const getAccountById = `-- name: GetAccountById :one
SELECT id, name, type, bank, balance_cents
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccountById(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Bank,
		&i.BalanceCents,
	)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, name, type, bank, balance_cents
FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Bank,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllReceipts = `-- name: GetAllReceipts :many
SELECT id, amount_cents, date, description
FROM receipts
ORDER BY id DESC
`

func (q *Queries) GetAllReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.QueryContext(ctx, getAllReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.AmountCents,
			&i.Date,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT value
FROM app_settings
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetAppSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getReceiptById = `-- name: GetReceiptById :one
SELECT id, amount_cents, date, description
FROM receipts
WHERE id = ?
`

func (q *Queries) GetReceiptById(ctx context.Context, id int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptById, id)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.AmountCents,
		&i.Date,
		&i.Description,
	)
	return i, err
}

const getTotalBalance = `-- name: GetTotalBalance :one
SELECT CAST(COALESCE(SUM(balance_cents), 0) AS INTEGER)
FROM accounts
`

func (q *Queries) GetTotalBalance(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalBalance)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalSpent = `-- name: GetTotalSpent :one
SELECT CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER)
FROM receipts
`

func (q *Queries) GetTotalSpent(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSpent)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getTotalSpentByDateRange = `-- name: GetTotalSpentByDateRange :one
SELECT CAST(COALESCE(SUM(amount_cents), 0) AS INTEGER)
FROM receipts
WHERE date >= ?
  AND date <= ?
`

type GetTotalSpentByDateRangeParams struct {
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

func (q *Queries) GetTotalSpentByDateRange(ctx context.Context, arg GetTotalSpentByDateRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalSpentByDateRange, arg.Date, arg.Date_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setAppSetting = `-- name: SetAppSetting :exec

INSERT OR
REPLACE
INTO app_settings (key, value)
VALUES (?, ?)
`

type SetAppSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// iceberg/database/queries/query.sql
func (q *Queries) SetAppSetting(ctx context.Context, arg SetAppSettingParams) error {
	_, err := q.db.ExecContext(ctx, setAppSetting, arg.Key, arg.Value)
	return err
}
